# Generated by Django 2.2.16 on 2022-05-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
