# Generated by Django 2.2.16 on 2022-05-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20220504_2134'),
        ('reviews', '0009_auto_20220504_2244'),
    ]

    operations = [
    ]
